### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = '/path/to/trained_wts.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by harshalsojitra** [jhasuman/potholes-detection#14]
Traceback (most recent call last):
  File "predict.py", line 96, in <module>
    _main_(args)
  File "predict.py", line 56, in _main_
    yolo.load_weights(weights_path)
  File "D:\potholes-detection-master\potholes-detection-master\frontend.py", line 243, in load_weights
    self.model.load_weights(weight_path)
  File "I:\Anaconda\lib\site-packages\keras\engine\network.py", line 1157, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "I:\Anaconda\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "I:\Anaconda\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/path/to/trained_wts.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by maverick-27** [comment]
Same issue 
OSError: Unable to open file (unable to open file: name = 'C:\Users\abc\Downloads\car\logs', errno = 13, error message = 'Permission denied', flags = 0, o_flags = 0)
